version: '3.8'

services:
  web-1:
    image: httpd:2.4
    container_name: web-1
    ports:
      - "8081:80"
    volumes:
      - ./public:/usr/local/apache2/htdocs/

  web-2:
    image: httpd:2.4
    container_name: web-2
    ports:
      - "8082:80"
    volumes:
      - ./public:/usr/local/apache2/htdocs/

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - web-1
      - web-2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
